const CHOCOLATE_PRICE = 20;

const WATER_WITH_GAS_PRICE = 10;
const WATER_WITHOUT_GAS_PRICE = 15;

const CHIPS_PRICE = 25;

const WANILLA_ICE_CREAM_PRICE = 1;
const CHOCOLATE_ICE_CREAM_PRICE = 2;
const STRAWBERRY_ICE_CREAM_PRICE = 3;
const VOLUME_CUP_IN_GRAMS = 150;

const COFFEE_CAPPUCCINO_PRICE = 50;
const COFFEE_LATTE_PRICE = 50;
const COFFEE_AMERICANO_PRICE = 40;
const COFFEE_ESPRESSO_PRICE = 40;